apiVersion: nuclio.io/v1
kind: NuclioFunction
metadata:
  name: nuc-handler
  namespace: nuclio
spec:
  handler: "nuc-handler:NuclioHandler"
  runtime: "golang"
  build:
    path: .
  minReplicas: 1
  triggers:
    myRabbitMQTopic:
      kind: "rabbit-mq"
      url: "amqp://nuclio:crayfish@rabbitmq.default.svc.cluster.local:5672/"
      attributes:
        exchangeName: ""
        queueName: subPopQueue
        maxWorkers: 1
