
## File in progress -- A snippet for OTel collector configuration file to export traces to Jaeger
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  jaeger:
    endpoint: "jaeger-collector.observability.svc.cluster.local:14250"
    tls_enabled: false

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger]
