apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-aggregator
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-aggregator
  template:
    metadata:
      labels:
        app: go-aggregator
    spec:
      containers:
      - name: go-aggregator
        image: pollardskangaroo/go-aggregator:latest 
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"