apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
spec:
  strategy: production
  collector:
    maxReplicas: 3
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
  ui: # Configuring the Jaeger UI
    options:
      dependencies:
        menuEnabled: false
        dagMaxNumServices: 200
      monitor:
        menuEnabled: false
      archiveEnabled: false
      tracking:
        gaID: UA-000000-2
        trackErrors: ture
        customWebAnalytics: null
      menu:
      - label: "About Jaeger"
        items:
          - label: "Documentation"
            url: "https://www.jaegertracing.io/docs/latest"
      linkPatterns:
      - type: "logs"
        key: "customer_id"
        url: /search?limit=20&lookback=1h&service=frontend&tags=%7B%22customer_id%22%3A%22#{customer_id}%22%7D
        text: "Search for other traces for customer_id=#{customer_id}"
      search:
        maxLimit: 100
        maxLookback: "2d"
  #storage: -----> Default will store trace data in memory
    #type: elasticsearch
    #options:
      #es:
        #server-urls: http://elasticsearch:9200
