apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nuclio-function-scaler
  namespace: nuclio
spec:
  scaleTargetRef: # Target is the nuclio function - scale it with respect to the queue's length
    kind: Deployment 
    name: nuclio-nuc-handler
  pollingInterval: 1 
  cooldownPeriod: 30 
  minReplicaCount: 1  
  maxReplicaCount: 10 # maximum replicas of nuclio function (for testing)
  triggers:
  - type: rabbitmq
    metadata:
      queueName: subPopQueue 
      host: amqp://nuclio:crayfish@rabbitmq.default.svc.cluster.local:5672/ # RabbitMQ connection string
      mode: QueueLength
      value: "1" # Target per instance 
