apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rabbitmq
  labels:
    team: backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: rabbitmq
  endpoints:
  - port: metrics # Port name in rabbitmq's service where metrics are exposed
    interval: 10s