apiVersion: apps/v1
kind: Deployment
metadata:
  name: func-aggregate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: func-aggregate
  template:
    metadata:
      labels:
        app: func-aggregate
    spec:
      containers:
      - name: func-aggregate
        image: arthurmerlin/func-aggregate:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"